spring:
  application:
    name: notebook
#  zipkin:
#    base-url: http://${ZIPKIN_SERVER}:${ZIPKIN_SERVER_PORT}
server:
#  context-path: /notebook
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone:  ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    preferIpAddress: true