spring:
  application:
    name: registry
  cloud:
    config:
      uri: http://${CONFIG_SERVER}:${CONFIG_SERVER_PORT}
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
