spring:
  application:
    name: gateway-server
info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
#  prefix: /
  routes:
    notebook:
      path: /notebook/**
      url: http://notebook:8080


ribbon:
  eureka:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone:  ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
    registerWithEureka: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
